# Generated by Django 4.2.14 on 2024-08-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eveYear',
            field=models.IntegerField(),
        ),
    ]
