# Generated by Django 4.2.14 on 2024-08-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgEvents', '0002_alter_event_eveyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eveImg',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
